export enum UserType {
    USER = "user",
    ADMIN = "ADMIN",
    
  }
  
  export enum Profile {
    ROLE_UNKNOW="ROLE_UNKNOW",
    ROLE_ADMIN_AGENCE="ROLE_ADMIN_AGENCE",
    ROLE_CANDIDAT="ROLE_CANDIDAT",
    ROLE_ADMIN="ROLE_ADMIN",
    ROLE_MEMBRE_EQUIPE="ROLE_MEMBRE_EQUIPE",
    ROLE_PROPRIETAIRE="ROLE_PROPRIETAIRE",
    ROLE_AGENT_IMMOBILIER="ROLE_AGENT_IMMOBILIER",
    ROLE_LOCATAIRE="ROLE_LOCATAIRE",
    ROLE_CONFIGURATEUR="ROLE_CONFIGURATEUR"
  }
  